### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by Jo-the-bat** [THLO/map#2]
Hello there, I still have a problem with the module
![python](https://user-images.githubusercontent.com/71979846/94478064-06475f00-01d3-11eb-99f7-dc0f9fbe183b.PNG)
![tempsnip](https://user-images.githubusercontent.com/71979846/94478568-bae18080-01d3-11eb-9fba-ce2c61a3b4d5.png)
I'm using Pyzo, I tried to execute with and without automatic indentations, changing settings and putting tabs and its not working (changing a tab seems to create other tab errors in other places as well). I can't understand the program and its tabs because it is not my level, could you help me please?

**Comment by Lescurel** [comment]
Apply a formatter ([`black`](https://pypi.org/project/black/) or [`autopep8`](https://pypi.org/project/autopep8/)) to the file that causes problems. 

In the command line interface:
```
autopep8 -i file.py

**Comment by THLO** [comment]
This problem should also be fixed in version 1.2.1.
